version: '3.8'

# This docker-compose is for development only
# For production, the docker-compose.prod.yml will be defined in portainer.io

services:
  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    container_name: co-op-mode-api
    restart: unless-stopped
    environment:
      DOMAIN: localhost
      NODE_ENV: development
      SESSION_ENCRYPTION_KEY: 12345
      DATABASE_URL: postgres://postgres:postgres@co-op-mode-postgres:5432/postgres
      REDIS_URL: redis://co-op-mode-redis:6379
      API_PORT: 80
    depends_on:
      - database
      - redis
    volumes:
      - type: bind
        source: "./api"
        target: "/app"
    command: yarn run dev
    ports:
      - 3000:80
    networks:
      - default

  routines:
    build:
      context: .
      dockerfile: ./routines/Dockerfile
    container_name: co-op-mode-routines
    restart: unless-stopped
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://postgres:postgres@co-op-mode-postgres:5432/postgres
      REDIS_URL: redis://co-op-mode-redis:6379
    depends_on:
      - api
      - database
      - redis
    volumes:
      - type: bind
        source: "./routines"
        target: "/app"
    command: yarn run dev
    networks:
      - default

  database:
    image: postgres:16.1-bullseye
    container_name: co-op-mode-postgres
    restart: unless-stopped
    user: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - default

  redis:
    image: redis:latest
    container_name: co-op-mode-redis
    restart: unless-stopped
    networks:
      - default
    volumes:
      - redis-data:/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: co-op-mode-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@navarrotech.net
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - 5050:80
    networks:
      - default
    depends_on:
      - database
    volumes:
      - ./pgadmin4/servers.json:/pgadmin4/servers.json
      - ./pgadmin4/pgpassfile:/pgpassfile
      - pgadmin-data:/var/lib/pgadmin

volumes:
  postgres-data:
  pgadmin-data:
  redis-data:
 
networks:
  default:
