// Copyright © 2024 Navarrotech

export const defaultLanguage = 'en' as const

export const supportedLanguages = [
  'en',
  'es',
  'fr',
  'ja'
] as const

export type SupportedLanguages = typeof supportedLanguages[number]

export const languageToFlag: Record<LanguageRecordKey, string> = {
  'en': 'US',
  'es': 'ES',
  'fr': 'FR',
  'ja': 'JP'
} as const

export const languageRecord: Record<string, string> = {
  en: 'English',
  zh: 'Chinese',
  es: 'Spanish',
  ar: 'Arabic',
  hi: 'Hindi',
  fr: 'French',
  ru: 'Russian',
  pt: 'Portuguese',
  de: 'German',
  ja: 'Japanese',
  ko: 'Korean',
  vi: 'Vietnamese',
  it: 'Italian',
  tr: 'Turkish',
  pl: 'Polish',
  uk: 'Ukrainian',
  nl: 'Dutch',
  th: 'Thai',
  sv: 'Swedish',
  da: 'Danish',
  fi: 'Finnish',
  no: 'Norwegian',
  he: 'Hebrew',
  el: 'Greek',
  hu: 'Hungarian',
  cs: 'Czech',
  ro: 'Romanian',
  bg: 'Bulgarian',
  sk: 'Slovak',
  lt: 'Lithuanian',
  lv: 'Latvian',
  et: 'Estonian',
  hr: 'Croatian',
  sl: 'Slovenian',
  sr: 'Serbian',
  mk: 'Macedonian',
  bs: 'Bosnian',
  mt: 'Maltese',
  is: 'Icelandic',
  ga: 'Irish',
  cy: 'Welsh',
  be: 'Belarusian',
  hy: 'Armenian',
  ka: 'Georgian',
  az: 'Azerbaijani',
  eu: 'Basque',
  ca: 'Catalan',
  gl: 'Galician',
  sq: 'Albanian',
  mn: 'Mongolian',
  ur: 'Urdu',
  fa: 'Persian',
  ta: 'Tamil',
  te: 'Telugu',
  ml: 'Malayalam',
  kn: 'Kannada',
  mr: 'Marathi',
  gu: 'Gujarati',
  pa: 'Punjabi',
  bn: 'Bengali',
  my: 'Burmese',
  km: 'Khmer',
  lo: 'Lao',
  si: 'Sinhala'
} as const

export const languageLocalizedRecord: Record<string, string> = {
  en: 'English',
  zh: '中文',
  es: 'Español',
  ar: 'العربية',
  hi: 'हिन्दी',
  fr: 'Français',
  ru: 'Русский',
  pt: 'Português',
  de: 'Deutsch',
  ja: '日本語',
  ko: '한국어',
  vi: 'Tiếng Việt',
  it: 'Italiano',
  tr: 'Türkçe',
  pl: 'Polski',
  uk: 'Українська',
  nl: 'Nederlands',
  th: 'ไทย',
  sv: 'Svenska',
  da: 'Dansk',
  fi: 'Suomi',
  no: 'Norsk',
  he: 'עברית',
  el: 'Ελληνικά',
  hu: 'Magyar',
  cs: 'Čeština',
  ro: 'Română',
  bg: 'Български',
  sk: 'Slovenčina',
  lt: 'Lietuvių',
  lv: 'Latviešu',
  et: 'Eesti',
  hr: 'Hrvatski',
  sl: 'Slovenščina',
  sr: 'Српски',
  mk: 'Македонски',
  bs: 'Bosanski',
  mt: 'Malti',
  is: 'Íslenska',
  ga: 'Gaeilge',
  cy: 'Cymraeg',
  be: 'Беларуская',
  hy: 'Հայերեն',
  ka: 'ქართული',
  az: 'Azərbaycan',
  eu: 'Euskara',
  ca: 'Català',
  gl: 'Galego',
  sq: 'Shqip',
  mn: 'Монгол',
  ur: 'اردو',
  fa: 'فارسی',
  ta: 'தமிழ்',
  te: 'తెలుగు',
  ml: 'മലയാളം',
  kn: 'ಕನ್ನಡ',
  mr: 'मराठी',
  gu: 'ગુજરાતી',
  pa: 'ਪੰਜਾਬੀ',
  bn: 'বাংলা',
  my: 'မြန်မာဘာသာ',
  km: 'ខ្មែរ',
  lo: 'ລາວ',
  si: 'සිංහල'
} as const

type LanguageRecordKey = keyof typeof languageRecord
