// Copyright © 2024 Navarrotech

export const defaultLanguage = "en" as const

export const supportedLanguages = [
    "en", "zh", "es", "ar", "hi", "fr", "ru", "pt", "de", "ja", "ko", "vi", "it", "tr", "pl", "uk", 
    "nl", "th", "sv", "da", "fi", "no", "he", "el", "hu", "cs", "ro", "bg", "sk", "lt", "lv", "et",
    "hr", "sl", "sr", "mk", "bs", "mt", "is", "ga", "cy", "be", "hy", "ka", "az", "eu", "ca", "gl", 
    "sq", "mn", "ur", "fa", "ta", "te", "ml", "kn", "mr", "gu", "pa", "bn", "my", "km", "lo", "si"
] as const

export type SupportedLanguages = typeof supportedLanguages[number]

export const languageRecord: Record<string, string> = {
    en: "English",
    zh: "Chinese",
    es: "Spanish",
    ar: "Arabic",
    hi: "Hindi",
    fr: "French",
    ru: "Russian",
    pt: "Portuguese",
    de: "German",
    ja: "Japanese",
    ko: "Korean",
    vi: "Vietnamese",
    it: "Italian",
    tr: "Turkish",
    pl: "Polish",
    uk: "Ukrainian",
    nl: "Dutch",
    th: "Thai",
    sv: "Swedish",
    da: "Danish",
    fi: "Finnish",
    no: "Norwegian",
    he: "Hebrew",
    el: "Greek",
    hu: "Hungarian",
    cs: "Czech",
    ro: "Romanian",
    bg: "Bulgarian",
    sk: "Slovak",
    lt: "Lithuanian",
    lv: "Latvian",
    et: "Estonian",
    hr: "Croatian",
    sl: "Slovenian",
    sr: "Serbian",
    mk: "Macedonian",
    bs: "Bosnian",
    mt: "Maltese",
    is: "Icelandic",
    ga: "Irish",
    cy: "Welsh",
    be: "Belarusian",
    hy: "Armenian",
    ka: "Georgian",
    az: "Azerbaijani",
    eu: "Basque",
    ca: "Catalan",
    gl: "Galician",
    sq: "Albanian",
    mn: "Mongolian",
    ur: "Urdu",
    fa: "Persian",
    ta: "Tamil",
    te: "Telugu",
    ml: "Malayalam",
    kn: "Kannada",
    mr: "Marathi",
    gu: "Gujarati",
    pa: "Punjabi",
    bn: "Bengali",
    my: "Burmese",
    km: "Khmer",
    lo: "Lao",
    si: "Sinhala"
} as const
